# PLOG-HEXO
footer: 
  shuoming: 记录美好生活
  author: 爱谁谁
  title: 关于我
  information: 移植自heo的PLOG

favicon: https://img.zhheo.com/i/2022/10/08/6340fc3173131.png
logo: https://img.zhheo.com/i/2022/10/08/6340fc3173131.png
